services:
  squidex_mongo:
    image: "mongo:6"
    volumes:
      - ./data/mongo:/data/db
    networks:
      - internal
    restart: unless-stopped

  squidex_squidex:
    image: "squidex/squidex:7"
    ports:
      - "8090:80"
    environment:
      - URLS__BASEURL=http://localhost:8090
      - EVENTSTORE__TYPE=MongoDB
      - EVENTSTORE__MONGODB__CONFIGURATION=mongodb://squidex_mongo
      - STORE__MONGODB__CONFIGURATION=mongodb://squidex_mongo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/healthz"]
      start_period: 60s
    depends_on:
      - squidex_mongo
    volumes:
      - ./data/assets:/app/Assets
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - internal
    restart: unless-stopped

networks:
  internal:
    driver: bridge
